spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes[0]:
        id: auth-service
        uri: lb://auth-service
        predicates[0]: Path=/api/v1/auth

        routes[1]:
          id: hotel-service
          uri: lb://hotel-service
          predicates[0]: Path=/api/v1/hotel

        routes[2]:
          id: room-service
          uri: lb://room-service
          predicates[0]: Path=/api/v1/room

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

















logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE