spring:
  application:
    name: hotel-service


  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hotel_service?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8083
#  servlet:
#    context-path: /hotel-service